sudo: required
services:
  - docker

before_install:
  - docker build -t vrusu/docker-frontend -f Dockerfile.dev .

script:
  - docker run vrusu/docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-eu-west-2-957517018670"
  bucket_path: "docker-react"  #app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY